#!/bin/sh
set -e
make

echo "Validate: base"
make clean-tests && make -B test-all $@

echo "Validate: -DDFIRSTCLASSLABELS"
make clean-tests && CFLAGS="-DFIRSTCLASSLABELS" make -B test-all $@

for KZCFLAGS in \
    "--fsimpl" \
    "--fsimpl --finline" \
    "--ffuse" \
    "--fpeval" \
    "--fsimpl --fpeval" \
    "--ffuse --fpeval" \
    "--fautolut --flut" \
    "--fautolut --flut --fpeval" \
    "--finline --fsimpl --fpeval --fautolut --flut" ; do
    echo "Validate: $KZCFLAGS"
    make clean-tests && KZCFLAGS="$KZCFLAGS" make -B test-all $@
done

make clean-tests
